### ISSUE TITLE
Snowflake v2.5.1 using event logger crashes Orbot

### ISSUE THREAD

**Issue by syphyr** [bitmold/OrbotIPtProxy#5]
I have been testing Orbot 16.6.4 RC1 with latest version of OrbotLib (IPtProxy 1.10.1) and snowflake crashes Orbot when snowflake is enabled.

```
02-09 20:54:01.738 27446 27472 F libc    : Fatal signal 6 (SIGABRT), code -6 in tid 27472 (project.android)
02-09 20:54:01.834 27476 27476 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
02-09 20:54:01.834 27476 27476 F DEBUG   : LineageOS Version: '14.1-20230207-NIGHTLY-gts210vewifi'
02-09 20:54:01.834 27476 27476 F DEBUG   : Build fingerprint: 'samsung/gts210vewifixx/gts210vewifi:7.0/NRD90M/T813XXU2BQD3:user/release-keys'
02-09 20:54:01.834 27476 27476 F DEBUG   : Revision: '4'
02-09 20:54:01.834 27476 27476 F DEBUG   : ABI: 'arm64'
02-09 20:54:01.834 27476 27476 F DEBUG   : pid: 27446, tid: 27472, name: project.android  >>> org.torproject.android <<<
02-09 20:54:01.834 27476 27476 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
02-09 20:54:01.834 27476 27476 F DEBUG   :     x0   0000000000000000  x1   0000000000006b50  x2   0000000000000006  x3   0000000000000008
02-09 20:54:01.834 27476 27476 F DEBUG   :     x4   0000000000000001  x5   0000000000000001  x6   0000000000000000  x7   000000000000000a
02-09 20:54:01.834 27476 27476 F DEBUG   :     x8   0000000000000083  x9   0000000000000067  x10  0000000000016ef3  x11  000000000a0032f6
02-09 20:54:01.834 27476 27476 F DEBUG   :     x12  0000000000000018  x13  ffffffff9c1c1f99  x14  00199bf1b6000000  x15  003b9aca00000000
02-09 20:54:01.834 27476 27476 F DEBUG   :     x16  0000007f34b65ae8  x17  0000007f34c60f90  x18  00000000ffffffff  x19  0000000000006b36
02-09 20:54:01.835 27476 27476 F DEBUG   :     x20  0000007f34c60e30  x21  000000400003dc00  x22  0000000000000001  x23  ffffffffffffffff
02-09 20:54:01.835 27476 27476 F DEBUG   :     x24  0000007f5ce27580  x25  00000000000fd000  x26  0000000000000000  x27  0000000000000190
02-09 20:54:01.835 27476 27476 F DEBUG   :     x28  00000040000021a0  x29  000000400004baf8  x30  0000007f5c9350c4
02-09 20:54:01.835 27476 27476 F DEBUG   :     sp   000000400004bb00  pc   0000007f5c9515f8  pstate 0000000080000000
02-09 20:54:01.836 27476 27476 F DEBUG   : 
02-09 20:54:01.836 27476 27476 F DEBUG   : backtrace:
02-09 20:54:01.836 27476 27476 F DEBUG   :     #00 pc 00000000001af5f8  /data/app/org.torproject.android-1/lib/arm64/libgojni.so
02-09 20:54:01.836 27476 27476 F DEBUG   :     #01 pc 00000000001930c0  /data/app/org.torproject.android-1/lib/arm64/libgojni.so
```

I bisected the issue to this snowflake commit: https://gitweb.torproject.org/pluggable-transports/snowflake.git/commit/?id=768b80dbdfba8733a614770c93fdbea4d48c7c52

There is a conflict with snowflake when it tries to use the event logger.  Reverting the commit above fixes the issue on Orbot 16.  I have not tested Orbot 17 yet, but I assume the same problem exists.

**Comment by syphyr** [comment]
Perhaps the crash is related to e.CurNATType not being defined.

```
02-09 22:33:51.358  2952  2997 E GoLog   : 2023/02/09 21:33:51 NAT Type measurement: unknown -> restricted = restricted
02-09 22:33:51.359  2952  2997 E GoLog   : 2023/02/09 21:33:51 NAT type: restricted
```

**Comment by bitmold** [comment]
Thanks for reporting this, I've seen at least one other kind of crash wtih Snowflake 2.5.1 in Orbot. 

Were you trying to use snowflake to connect to the tor network, or were you using your android device as a snowflake proxy for other people?

**Comment by syphyr** [comment]
Orbot would crash on my android device as soon as I enabled snowflake for other people.  When I enable bridges on Orbot, I noticed this ini the log:

```
02-09 22:35:38.898  2952  3003 I GoLog   : Feb 09 22:35:38.000 [notice] {CONTROL} Bootstrapped 100% (done): Done
02-09 22:35:43.039  2952  2997 E GoLog   : 2023/02/09 21:35:43 NAT Type measurement: restricted -> restricted = restricted
02-09 22:35:43.039  2952  2997 E GoLog   : 2023/02/09 21:35:43 NAT type: restricted
02-09 22:38:16.120  2952  2997 I GoLog   : Feb 09 22:38:16.000 [notice] {GENERAL} Interrupt: exiting cleanly.
02-09 22:38:23.942  2952  2996 I GoLog   : VERSION 1
02-09 22:38:23.942  2952  2996 I GoLog   : CMETHOD meek_lite socks5 127.0.0.1:47000
02-09 22:38:23.942  2952  2996 I GoLog   : CMETHOD obfs2 socks5 127.0.0.1:47100
02-09 22:38:23.942  2952  2996 I GoLog   : CMETHOD obfs3 socks5 127.0.0.1:47200
02-09 22:38:23.942  2952  2996 I GoLog   : CMETHOD obfs4 socks5 127.0.0.1:47300
02-09 22:38:23.942  2952  2996 I GoLog   : CMETHOD scramblesuit socks5 127.0.0.1:47400
02-09 22:38:23.942  2952  2996 I GoLog   : CMETHOD-ERROR snowflake no such transport is supported
02-09 22:38:23.942  2952  2996 I GoLog   : CMETHODS DONE
```

I'm not sure why the log says "snowflake no such transport is supported" when I enable bridges.  Maybe it always said that error and I never noticed because I don't test bridges often enough.

**Comment by bitmold** [comment]
That line doesn't have anything to do with crashes, it's from `obfs4proxy.go`.

```go
// Launch each of the client listeners.
	for _, name := range ptClientInfo.MethodNames {
		t := transports.Get(name)
		if t == nil {
			_ = pt.CmethodError(name, "no such transport is supported")
			continue
		}
```

In IPtProxy all the transports we might use are set:
```go
_ = os.Setenv("TOR_PT_CLIENT_TRANSPORTS", "meek_lite,obfs2,obfs3,obfs4,scramblesuit,snowflake")
```

Then obfs4proxy iterates through all of them, it knows about obfs2,3,4, meek, and scamblesuit, but it doesn't know about snowflake. That line is not important, basically.

**Comment by syphyr** [comment]
When IPtProxy applies snowflake.patch, it changes the way logging is done.  I think this is why Orbot is crashing when snowflake is enabled and why this crash is not reproducible with snowflake when not using Orbot. 

My solution is to do this, since I think this crash is Orbot specific:
https://github.com/syphyr/IPtProxy/commit/76481a6c158b609b04eac6203a332b21fe667962
https://github.com/syphyr/OrbotIPtProxy/commit/c2a8ab285857c5a618891b2d63a05fa70362d4e2

**Comment by syphyr** [comment]
I just had a chance to test Orbot 17 and it appears that Orbot 17 is not affected by this issue, only Orbot 16.  So, perhaps this is not a priority.  There are a few changes with snowflake logging in Orbot 16 that was never added to Orbot 17.

Orbot 16:
IPtProxy.startSnowflake(stunServers, target, front, null, logFile, logToStateDir, keepLocalAddresses, unsafeLogging, maxPeers);

Orbot 17:
IPtProxy.startSnowflake(stunServer, target, front, null, null, true, false, false, 1);

**Comment by syphyr** [comment]
Thank you, your upstream commit (https://github.com/tladesignz/IPtProxy/commit/4a82ef6e18cd8e61c84982da67555936194d425c) fixes this issue.

**Comment by bitmold** [comment]
> Perhaps the crash is related to e.CurNATType not being defined.

This just happens sometimes when running a snowflake proxy (on desktop) by the way. 

For the record, I was producing this crash on v17 - but it was from running a snowflake proxy. The method you commented above `IPtProxy.startSnowflake(...` is for using snowflake (being a client), not running a proxy and from what I could tell your modifications to the patch files didn't touch the client code so I'm a bit curious about whatever was happening to you. 

In any case, since both proxy and client work now in Orbot 17 - we can close this issue

**Comment by syphyr** [comment]
It was the proxy crashing for me. The client side was fine. I was only trying to figure out differences b/n 16 and 17.
