### ISSUE TITLE
IPtProxy.go undefined: obfs4proxy

### ISSUE THREAD

**Issue by syphyr** [bitmold/OrbotIPtProxy#7]
OrbotIPtProxy fails to build with the following error:

```
OrbotIPtProxy/IPtProxy/IPtProxy.go/IPtProxy.go:100:9: undefined: obfs4proxy
gomobile: go build -v -trimpath -buildmode=c-shared -o=/tmp/gomobile-work-3907180380/android/src/main/jniLibs/arm64-v8a/libgojni.so ./gobind failed: exit status 1
```

The problem is that obfs4proxy was removed from IPtProxy.go here: https://github.com/tladesignz/IPtProxy/commit/98299c9a8d0efefd7b4088936ece54b655c3195b

I have opened a PR on IPtProxy:
https://github.com/tladesignz/IPtProxy/pull/43

**Comment by bitmold** [comment]
Thanks, I'm sure @tladesignz will merge it soon and then I'll make a new release of Orbotlib. Since this is an issue with IPtProxy and not the Orbot wrapper, I'm closing this issue.
